services:
    bb3mobi.AvatarUpload.listener:
        class: bb3mobi\AvatarUpload\event\listener
        arguments:
            - @user
            - @request
            - @dbal.conn
            - @bb3mobi.AvatarUpload.resize
        tags:
            - { name: event.listener }
    bb3mobi.AvatarUpload.resize:
        class: bb3mobi\AvatarUpload\core\resize
        arguments:
            - @config
            - @user
            - @mimetype.guesser
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
    bb3mobi.AvatarUpload.crop:
        class: bb3mobi\AvatarUpload\controller\crop
        arguments:
            - @template
            - @config
            - @user
            - @request
            - @dbal.conn
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
